# Generated by Django 2.1.7 on 2021-02-09 15:51

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', timezone_field.fields.TimeZoneField()),
            ],
        ),
        migrations.AddField(
            model_name='activity_periods',
            name='Members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity_Periods', to='testapp.members'),
        ),
    ]
