# Generated by Django 2.1.7 on 2021-02-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210209_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_periods',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity_periods',
            name='start_time',
        ),
    ]
