# Generated by Django 2.1.7 on 2021-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20210209_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_periods',
            name='end_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity_periods',
            name='start_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
